const en = {
  appName: 'Construction Project Management System (CPMS)',

  dashboard: 'Dashboard',
  definitions: 'Definitions',
  planning: 'Planning',
  transactions: 'Transactions',
  reports: 'Reports',

  users: 'Users',
  projects: 'Projects',
  itemClassifications: 'Item Classifications',
  items: 'Items',
  delivery: 'Delivery',
  installation: 'Installation',
  inspection: 'Inspection',
  companies: 'Companies',
  positionRoles: 'Position Roles',

  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  search: 'Search...',
  loading: 'Loading...',
  saving: 'Saving...',
  confirm: 'Confirm',

  login: 'Sign In',
  logout: 'Logout',
  username: 'Username',
  password: 'Password',
  newPassword: 'New Password',
  leaveBlankPassword: 'Leave blank to keep current password',
  loginSubtitle: 'Sign in to your account',
  selectCompany: 'Select Company',
  selectCompanyPrompt: 'You have access to multiple companies. Please select one to continue.',
  continueBtn: 'Continue',

  fullName: 'Full Name',
  fullNameAr: 'Full Name (Arabic)',
  fullNameEn: 'Full Name (English)',
  role: 'Role',
  positionRole: 'Position Role',
  email: 'Email',
  status: 'Status',
  active: 'Active',
  inactive: 'Inactive',
  addUser: 'Add User',
  editUser: 'Edit User',
  profilePicture: 'Profile Picture',
  roles: {
    admin: 'Admin',
    project_manager: 'Project Manager',
    site_engineer: 'Site Engineer',
  },

  pagePermissions: 'Page Permissions',
  projectAccess: 'Project Access',
  permissionsNote: 'Admin has full access — permissions apply to PM and Site Engineer only.',

  companyNameAr: 'Company Name (Arabic)',
  companyNameEn: 'Company Name (English)',
  companyType: 'Company Type',
  companyTypeOrg: 'Organization',
  companyTypeHolding: 'Holding Company',
  taxId: 'Tax ID',
  parentCompany: 'Parent Holding Company',
  noParent: '— None (Top Level) —',
  addCompany: 'Add Company',
  editCompany: 'Edit Company',

  positionRoleNameAr: 'Position Name (Arabic)',
  positionRoleNameEn: 'Position Name (English)',
  addPositionRole: 'Add Position Role',
  editPositionRole: 'Edit Position Role',

  projectCode: 'Project Code',
  projectNameEn: 'Project Name (English)',
  projectNameAr: 'Project Name (Arabic)',
  location: 'Location',
  client: 'Client',
  startDate: 'Start Date',
  endDate: 'End Date',
  manager: 'Manager',
  addProject: 'Add Project',
  editProject: 'Edit Project',
  statuses: {
    active: 'Active',
    completed: 'Completed',
    on_hold: 'On Hold',
    cancelled: 'Cancelled',
  },

  classificationCode: 'Code',
  classificationName: 'Name',
  parentClassification: 'Parent Classification',
  topLevel: '— Top Level —',
  addClassification: 'Add Classification',
  editClassification: 'Edit Classification',

  itemCode: 'Item Code',
  itemName: 'Item Name',
  classification: 'Classification',
  unitOfMeasure: 'Unit',
  addItem: 'Add Item',
  editItem: 'Edit Item',

  plannedQty: 'Planned Qty',
  planningTitle: 'Project Planning',
  selectProjectToStart: 'Select a project to set up its planned quantities',
  noItemsAvailable: 'No active items available. Add items in Definitions first.',
  savePlanning: 'Save Planning',

  selectProject: 'Select Project',
  allProjects: 'All Projects',
  selectDate: 'Select Date',
  qtyDelivered: 'Qty Delivered',
  qtyInstalled: 'Qty Installed',
  qtyInspected: 'Qty Inspected',
  deliveryRef: 'Delivery Ref',
  notes: 'Notes',
  remarks: 'Remarks',
  inspectionStatus: 'Result',
  totalDelivered: 'Total Delivered',
  totalInstalled: 'Total Installed',
  totalInspected: 'Total Inspected',
  progress: 'Progress',
  saveEntries: 'Save Entries',
  noItemsLinked: 'No items have been planned for this project yet.',

  totalProjects: 'Total Projects',
  installationProgress: 'Installation Progress',
  deliveryProgress: 'Delivery Progress',
  inspectionProgress: 'Inspection Progress',
  passRate: 'Pass Rate',
  installationByItem: 'Installation by Item',
  deliveryByItem: 'Delivery by Item',
  inspectionResults: 'Inspection Results',
  planned: 'Planned',
  installed: 'Installed',
  delivered: 'Delivered',
  inspected: 'Inspected',
  pass: 'Pass',
  fail: 'Fail',
  pending: 'Pending',

  reportProgress: 'Planning vs Delivery vs Installation',
  reportProjectsSummary: 'Project Summary',
  reportItemTracking: 'Item Tracking',
  reportInspection: 'Inspection Report',
  installPct: 'Install %',
  deliveryPct: 'Delivery %',

  confirmDelete: 'Are you sure you want to delete this record? This cannot be undone.',
  noData: 'No data available',
  errorOccurred: 'An error occurred. Please try again.',
  saveSuccess: 'Saved successfully',
  deleteSuccess: 'Deleted successfully',
};

export default en;